api:
  insecure: true
  dashboard: true

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: guiguidu82@laposte.net
      storage: /letsencrypt/acme.json