version: '3.8'

services:  
  mqtt-broker:
    image: eclipse-mosquitto:2.0.20
    container_name: mqtt-broker
    ports:
      - "1883:2883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto
