services:  
  mqtt-broker:
    image: eclipse-mosquitto:2.0.20
    restart: always
    container_name: mqtt-broker
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3", "-h", "127.0.0.1", "-p", "1880"]
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - type: bind
        source: ./MQTT-broker/mosquitto/
        target: /mosquitto
  home-assistant:
    image: homeassistant/home-assistant:2024.12
    container_name: home-assistant
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - ./home-assistant:/config
    environment:
      - TZ=Europe/Paris
  redis-cache:
    image: redis:6.2-alpine
    restart: always
    container_name: redis-cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 --loglevel debug
    volumes: 
      - redis-cache:/data
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - '5540:5540'
    environment:
      - REDISINSIGHT_REDIS_URI=redis://redis-cache:6379
  simulator:
    build: ../esp32-devices/simulation
    environment:
      MQTT_BROKER_URL: mqtt://mqtt-broker:1883
      DATA_FREQUENCY: ${DATA_FREQUENCY:-5000}
      SENSOR_COUNT: ${SENSOR_COUNT:-4}
      MQTT_QOS: ${MQTT_QOS:-0}
    env_file:
    - ../esp32-devices/simulation/.env
    depends_on:
      mqtt-broker:
        condition: service_healthy
    networks:
      - default
  python:
    image: python:3.13
    container_name: python
    working_dir: /app
    volumes:
      - ./manager/:/app
    command: sh -c "pip install -r /app/requirements.txt && python /app/main.py"
  script-launcher:
    image: alpine:3.14
    container_name: script-launcher
    volumes:
      - ./script-launcher/:/app
    command: sh -c "apk add --no-cache bash && bash /app/start.bash"
    networks:
      - default
      - public-server_dev


volumes:
  redis-cache:
    driver: local
    name: redis-cache

networks:
  public-server_dev:
    external: true