version: '3.8'

services:  
  mqtt-broker:
    build:
      context: ./MQTT-broker
      dockerfile: Dockerfile
    container_name: mqtt-broker
    ports:
      - "1883:2883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto



volumes:
  mosquitto_data:
    driver: local